### ISSUE TITLE
Don't use sourceforge

### ISSUE THREAD

**Issue by thomassross** [WinT-3794/QDriverStation#12]
Sourceforge has been going downhill in quality recently, uBlock Origin blocks it as a ["badware risk"](https://github.com/gorhill/uBlock/wiki/Badware-risks#sourceforgenet). I suggest you use GitHub's release system to host binaries instead.

**Comment by alex-spataru** [comment]
Thanks for the information, I will transfer the installers to GitHub. I will keep the SF project open so that it redirects to the official website.

**Comment by alex-spataru** [comment]
I moved the installers to GitHub and updated the official website with the appropriate download links.

**Comment by thomassross** [comment]
Thanks!
