### ISSUE TITLE
[Linux] SDL detects external mouse as joystick

### ISSUE THREAD

**Issue by alex-spataru** [WinT-3794/QDriverStation#13]
While testing the QDriverStation on Linux (Ubuntu 14.04), I encountered a rather strange issue: SDL detects my external mouse as a joystick. Luckily, mouse movements did not affect at all the axes/buttons displayed in the Joysticks tab.

My idea to solve this issue is to create an option to 'blacklist' certain devices (using their UUID) and possibly, be able to upload the blacklist online, so that other QDriverStation installations use the online list as a reference.

Has anyone else encountered this issue? If so, what are your proposed solutions?

**Comment by BearzRobotics** [comment]
This is odd. I'v never encountered this before.

**Comment by alex-spataru** [comment]
Attaching screenshot for further reference. 
![mousebug](https://cloud.githubusercontent.com/assets/4225542/13313424/512a7a2a-db63-11e5-944b-1bc17d996926.png)

**Comment by alex-spataru** [comment]
I've added an option to blacklist/whitelist the selected joystick in the latest commit. Its the best solution that I can come up with for the moment.
