### ISSUE TITLE
Project Icon/Logo competition

### ISSUE THREAD

**Issue by alex-spataru** [WinT-3794/QDriverStation#19]
Since this project has started, it used the logo of FIRST as its primary icon. However, this can get us in trouble with the branding policy of FIRST, since we cannot verify that every contributor and user of this project is related to FIRST. Also, the logo of FIRST can be used in many projects and does not really represent a Driver Station application....

Since I suck at designing, I would like to invite you to design and submit an icon for this project. After several submissions, the community shall vote for the best icon.

**Comment by everylittlebit** [comment]
Wow, this looks like an interesting project that I will definitely be notifying my team of, here is a quick logo idea, 
![My Submission](http://i.imgur.com/0GWgMVq.jpg)
Cheers from team 2702

**Comment by Jelomite** [comment]
I don't know if I should stay with the FIRST colors or not, anyways, here the idea:

![untitled-2](https://cloud.githubusercontent.com/assets/18540571/14621660/214e3fa0-05cd-11e6-95ea-08d6c5b0e24b.png)

Good luck :smiley:

**Comment by alex-spataru** [comment]
This logo was created by [Jelomite](http://github.com/jelomite).
I received an e-mail notification but somehow his/her contribution is not displayed here, so I am re-uploading the design here.

![214e3fa0-05cd-11e6-95ea-08d6c5b0e24b](https://cloud.githubusercontent.com/assets/4225542/14623487/5a602112-0598-11e6-84ea-0697489c98f5.png)

@everylittlebit Thanks for your contribution! I like that icon!

**Comment by Jelomite** [comment]
@alex-spataru It seems that I accidently deleted the comment, I'm kinda new to gitHub. Thanks for reuploading!

**Comment by andrewda** [comment]
@Jelomite the logo looks great!

**Comment by Jelomite** [comment]
@andrewda Thank you!

**Comment by alex-spataru** [comment]
@Jelomite I also like your logo, do you think that you can upload a version with a transparent background?

**Comment by Jelomite** [comment]
@alex-spataru  No problem, here it is:
![qdriverstation icon](https://cloud.githubusercontent.com/assets/18540571/14715889/531c7088-07f3-11e6-886d-89fa20774b55.png)

**Comment by alex-spataru** [comment]
@Jelomite Thanks!

**Comment by alex-spataru** [comment]
Based on an online [tutorial](http://gimpchat.com/viewtopic.php?f=23&t=4660), I created the this icon:

![qdriverstation](https://cloud.githubusercontent.com/assets/4225542/14998394/51d3320c-1149-11e6-9ead-21eb7ab80dd0.png)

Any opinions about it?

**Comment by alex-spataru** [comment]
And here is another variant of the logo with another font for the "Q"

![modern](https://cloud.githubusercontent.com/assets/4225542/14999226/8afa7c80-114d-11e6-9fbf-f797a07e1808.png)

**Comment by alex-spataru** [comment]
Does anyone have more comments on the logos?

**Comment by Jelomite** [comment]
@alex-spataru  The second one looks very neat, I love it.

**Comment by alex-spataru** [comment]
Thanks for the contributions and comments! The QDriverStation will use the icon provided by @Jelomite.
