### ISSUE TITLE
Selecting SmartDashboard on Linux opens JAR file as archive

### ISSUE THREAD

**Issue by lopsided98** [WinT-3794/QDriverStation#23]
When selecting either of the dashboards when running QDriverStation in GNOME on Linux (I'm not sure if this is specific to GNOME), the JAR file opens as an archive (in file-roller). This is because you start it using `xdg-open`. Is there a reason you use this rather than just calling `java -jar` like on Windows and Mac? When I changed it to use `java -jar` on Linux, it worked correctly.

**Comment by alex-spataru** [comment]
@lopsided98 Thanks for the report and contribution!
